In [1]:
import numpy as np
import pandas as pd

In [2]:
flats = pd.read_csv('D:/Real_State_Business_Project/datasets/flats_cleaned.csv')
houses = pd.read_csv('D:/Real_State_Business_Project/datasets/house_cleaned.csv')

In [3]:
df = pd.concat([flats,houses],ignore_index=True)

In [4]:
df = df.sample(df.shape[0],ignore_index=True)

In [5]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,0.72,6660.0,1081.0,Super Built up area 1081(100.43 sq.m.),3,2,3,not available,"Sector 36 Sohna, Gurgaon, Haryana",3.0,NaN,Under Construction,NaN,Residential apartment for sell.Located in sect...,[],NaN,NaN
1,3 BHK Flat in Sector 102 Gurgaon,flat,emaar gurgaon greens,1.42,8606.0,1650.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,others,"Sector 102 Gurgaon, Gurgaon, Haryana",4.0,North,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in DLF Phase 4,flat,dlf regency park,2.35,13224.0,1777.0,Super Built up area 1777(165.09 sq.m.)Built Up...,3,4,3,servant room,"000, DLF Phase 4, Gurgaon, Haryana",8.0,South-East,10+ Year Old,"['Dlf phase 1 metro station', 'Sector 42-43 me...",Check out this 3 bhk apartment for sale in dlf...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
3,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,3.05,9664.0,3156.0,Super Built up area 3156(293.2 sq.m.),4,5,3+,"servant room,others","Sector 69 Gurgaon, Gurgaon, Haryana",14.0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This lovely 4 bhk apartment/flat in sector 69 ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,emaar imperial gardens,1.98,9900.0,2000.0,Carpet area: 2000 (185.81 sq.m.),3,3,3+,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",9.0,North,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...","This is on dwarika express highway , the locat...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Connectivity3.5 out of 5', 'Management4.5 ou..."

In [6]:
df.shape

(3961, 20)

In [8]:
df.to_csv('D:/Real_State_Business_Project/datasets/gurgaon_properties.csv',index=False)